[package]
name = "fish-prompt"
version = "0.1.0"
authors = ["Jose Quintana <git.io/joseluisq>"]
license = "MIT OR Apache-2.0"
description = "Minimal Fish prompt with essentials. 🐠"
repository = "https://github.com/joseluisq/fish-prompt"
keywords = [
    "prompt",
    "fish-prompt",
    "fish-shell",
    "fish-packages"
]

[dependencies]
